services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: careerforge-postgres
    environment:
      POSTGRES_USER: careerforge
      POSTGRES_PASSWORD: careerforge
      POSTGRES_DB: careerforge
    ports:
      - "5440:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"

volumes:
  pgdata:
